SINGLE_CHECKS:
  GBDAT_EXP_ADD:
    value_conformance:
      range: ["01.01.1920", "01.06.2025"]

  GSCHL_EXP_ADD:
    value_conformance:
      range: ["m", "w"]

  ZNLMSVAGEW:
    value_conformance:
      range: [0.0, 500.0]

  ZNLMSVAEDA:
    value_conformance:
      range: ["01.01.1920", "01.06.2025"]
    temporal_order:
      after: GBDAT_EXP_ADD

COMPLEX_CHECKS:
  COMPUTATIONAL_CONFORMANCE:
    ["ZNLMSVAGEW", "ZNLMSVAGRO", "ZNLMSVABMI"]:
      formula: "ZNLMSVAGEW * ZNLMSVAGRO * ZNLMSVAGRO"
      result: "ZNLMSVABMI"
      eps: 0.1
